rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page, name='add_page'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/', views.restricted, name='restricted'),
    # url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^search/$', views.search, name='search'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^profiles/$', views.list_profiles, name='list_profiles'),
    url(r'^like_category/$', views.like_category, name='like_category'),
    url(r'^suggest/$', views.suggest_category, name='suggest_category'),
    url(r'^add/$', views.auto_add_page, name='auto_add_page'),
]

tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from rango import views

# need to set up serving media
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView


# Create a new class that redirects the user to the index page,
# if successful at logging
class MyRegistrationView(RegistrationView):

    def get_success_url(self, user):
        # return '/rango/'
        # add profile
        return '/rango/register_profile'




urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/$',
        MyRegistrationView.as_view(),
        name='registration_register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        if self.views < 0:
            self.views = 0
        if self.likes < 0:
            self.likes = 0
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Category, Page, UserProfile
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the categoty name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Pleas enter the title of page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ("category", )

    # def clean(self):
    #     cleaned_data = self.cleaned_data
    #     url = cleaned_data.get('url')
    #     print(url)
    #     print(type(url))
    #     if url and not url.startwith('http://'):
    #         url = 'http://' + url
    #         cleaned_data['url'] = url
    #
    #         return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('user',)

rango/views.py
from django.shortcuts import render, redirect
from rango.models import Category, Page, UserProfile
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from datetime import datetime
from rango.google_search import google_search


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).seconds > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        # visits = 1
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits


def index(request):
    request.session.set_test_cookie()
    # return render(request, 'rango/index.html', context=context_dict)

    # get 5 most liked categories
    category_list = Category.objects.order_by('-likes')[:5]

    # get 5 most viewed pages
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {'categories': category_list,
                    'pages': page_list}

    # return render(request, 'rango/index.html', context_dict)
#     instead return:

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context_dict)

    return response


def about(request):
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()

    print(request.method)
    print(request.user)
    name = "Koyynrad"
    context_dict = {'your_name': name}

    # return render(request, 'rango/about.html', context_dict)
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/about.html', context_dict)
    return response


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict["pages"] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    context_dict['query'] = category.name

    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = google_search(query, 5)
            if len(result_list) == 0:
                context_dict['not_find'] = 'not_find'

            context_dict['query'] = query
            context_dict['result_list'] = result_list

    return render(request, 'rango/category.html', context_dict)


@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            cat = form.save(commit=True)
            print(cat, cat.slug)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0

                try:
                    Page.objects.get(url=page.url)
                except Page.DoesNotExist:
                    page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    content_dict = {'form': form, 'category': category}

    return render(request, 'rango/add_page.html', content_dict)


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})


def search(request):
    result_list = 0
    if request.method == 'POST':
        query = request.POST['query'].strip()
        search_name = query
        if query:
            result_list = google_search(query, 5)
    else:
        search_name = ''
    return render(request, 'rango/search.html', {'result_list': result_list,
                                                 'search_name': search_name})


def track_url(request):
    url = '/rango/'
    if request.method == 'GET':
        print("GET metodh")
        if 'page_id' in request.GET:
            print("page _id in GEt")
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                print('znaleziono')
                page.views += 1
                page.save()
                url = page.url
            except:
                print("problem")
                pass
    return redirect(url)


@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect('rango:index')
        else:
            print(form.errors)
    context_dict = {'form': form}

    return render(request, 'rango/profile_registration.html', context_dict)


@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('rango:index')

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm(
        {'website': userprofile.website, 'picture': userprofile.picture})

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)

    return render(request, 'rango/profile.html',
                  {'userprofile': userprofile, 'selecteduser': user, 'form': form})


@login_required
def list_profiles(request):
    userprofile_list = UserProfile.objects.all()

    return render(request, 'rango/list_profiles.html',
                  {'userprofile_list': userprofile_list})


@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        # cat_id = request.GET.get('category_i.d', '0')
        likes = 0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()
            return HttpResponse(likes)
        else:
            return HttpResponse('dupa')


def get_category_list(max_results=0, start_with=''):
    cat_list = []
    if start_with:
        cat_list = Category.objects.filter(name__istartswith=start_with)

    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]
    return cat_list


def suggest_category(request):
    cat_list = []
    start_with = ''

    if request.method == 'GET':
        start_with = request.GET['suggestion']
    cat_list = get_category_list(8, start_with)

    return render(request, 'rango/cats.html', {'cats': cat_list})


@login_required
def auto_add_page(request):
    cat_id = None
    url = None
    title = None
    context_dict = {}
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        url = request.GET['url']
        title = request.GET['title']
        if cat_id:
            category = Category.objects.get(id=int(cat_id))
            p = Page.objects.get_or_create(category=category,
                                           title=title, url=url)
            pages = Page.objects.filter(category=category).order_by('-views')
            context_dict['pages'] = pages
    return render(request, 'rango/page_list.html',context_dict)

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
{{ add_category}}
{% endblock %}
{% block body_block %}
<h1>Add a Category</h1>
<div>
<form id="category_form" method="post" action="{% url 'rango:add_category' %}">
{% csrf_token %}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{% for field in form.visible_fields %}
{{ field.errors }}
{{ field.help_text }}
{{ field }}
{% endfor %}
<input type="submit" name="submit" value="Create Category" />
</form>
</div>
{% endblock %}

templates/rango/base.html
{#<!DOCTYPE html>#}
{#{% load staticfiles %}#}
{#<html lang="en">#}
{#  <head>#}
{#    <meta charset="utf-8">#}
{#    <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">#}
{#    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->#}
{#    <meta name="description" content="">#}
{#    <meta name="author" content="">#}
{#    <link rel="icon" href="http://v4-alpha.getbootstrap.com/favicon.ico">#}
{##}
{#   <title> Rango - {% block title %}How to Tango with Django!{% endblock %} </title>#}
{##}
{##}
{#    <!-- Bootstrap core CSS -->#}
{#    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">#}
{##}
{#    <!-- Custom styles for this template -->#}
{#    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">#}
{#  </head>#}
{##}
{#  <body>#}
{##}
{##}
{#          {% block body_block %}{% endblock %}#}
{#          {% block side_block %}{% endblock %}#}
{##}
{##}
{#    <!-- Bootstrap core JavaScript#}
{#    ================================================== -->#}
{#    <!-- Placed at the end of the document so the pages load faster -->#}
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>#}
{#    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>#}
{#    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>#}
{#    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->#}
{#    <script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/holder.min.js"></script>#}
{#    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->#}
{#    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>#}
{#  </body>#}
{#</html>#}







<!DOCTYPE html>
{% load staticfiles %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
{#<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>#}
<script src="{% static "js/rango-jquery.js" %}"></script>
<script src="{% static "js/rango-ajax.js" %}"></script>
{% load rango_template_tags %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,
initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="{% static 'images/favicon.ico' %}">
<title>
Rango - {% block title %}How to Tango with Django!{% endblock %}
</title>
<!-- Bootstrap core CSS -->
<link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"
rel="stylesheet">
<!-- Custom styles for this template -->
<link href=
"http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
<button type="button" class="navbar-toggler hidden-sm-up"
data-toggle="collapse" data-target="#navbar"
aria-expanded="false" aria-controls="navbar">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">Rango</a>
<div id="navbar">
<nav class="nav navbar-nav pull-xs-left">
<a class="nav-item nav-link" href="{% url 'rango:index' %}">Home</a>
<a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>
<a class="nav-item nav-link" href="{% url 'rango:search' %}">Search</a>
{#<a class="nav-item nav-link" href="{% url 'rango:search' %}">Search</a>#}
{% if user.is_authenticated %}
    <a class="nav-item nav-link" href="{% url 'rango:profile' user.username %}">Profile</a>
    <a class="nav-item nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a>
<a class="nav-item nav-link"
href="{% url 'rango:add_category' %}">
Add a New Category</a>
<a class="nav-item nav-link"
href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
{% else %}
<a class="nav-item nav-link"
href="{% url 'registration_register' %}">Register Here</a>
<a class="nav-item nav-link"
href="{% url 'auth_login' %}">Login</a>
{% endif %}
</nav>
</div>
</nav>
<div class="container-fluid">
<div class="row">
<div class="col-sm-3 col-md-2 sidebar">
{#sidebar#}
{#<div class="col-sm-3 sidebar">#}
<div>
<ul class="nav nav-list">
<li class="nav-header">Type to find a category</li>
    <form>
        <li><input class="search-query form-control" type="text"
            name="suggestion" value="" id="suggestion" />
        </li>
    </form>
</ul>
<hr>

<div id="cats">
</div>


{% block sidebar_block %}
{% get_category_list category %}
{% endblock %}
</div>
</div>
<div class="col-sm-9 offset-sm-2 col-sm-5 col-md-10 col-md-2 main">
{#<div class="col-sm-9">#}
    {% block body_block %}{% endblock %}
</div>

</div>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script
src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>
<script
src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
</script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script
src=
"http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.j\
s">
</script>
</body>
</html>
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{#<!DOCTYPE html>#}
{#{% load staticfiles %}#}
{#{% load rango_template_tags %}#}
{#<html>#}
{#<head>#}
{#<title>#}
{#Rango -#}
{#{% block title_block %}#}
{#How to Tango with Django!#}
{#{% endblock %}#}
{#</title>#}
{#</head>#}
{#<body>#}
{#<div>#}
{#{% block sidebar_block %}#}
{#    {% get_category_list category %}#}
{#{% endblock %}#}
{#</div>#}
{#<div>#}
{#{% block body_block %}#}
{#{% endblock %}#}
{#</div>#}
{#<hr />#}
{#<div>#}
{#<ul>#}
{#{% if user.is_authenticated %}#}
{#    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>#}
{#    <li><a href="{% url 'auth_logout' %}?next=/">Logout</a></li>#}
{#    <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>#}
{#{% else %}#}
{#    <li><a href="{% url 'auth_login' %}">Sign In</a></li>#}
{#    <li><a href="{% url 'registration_register' %}">Sign Uttp</a></li>#}
{#{% endif %}#}
{##}
{#    <li><a href="{% url 'rango:about' %}">About</a></li>#}
{#    <li><a href="{% url 'rango:index' %}">Index</a></li>#}
{##}
{#</ul>#}
{#</div>#}
{#</body>#}
{#</html>#}

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
{{ category.name }}
{% endblock %}
{% block body_block %}
{% if category %}
    {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br/>
    {% endif %}
<h1>{{ category.name }}</h1>

<div>
    <strong id="like_count">{{ category.likes }}</strong> people like this category
    {% if user.is_authenticated %}
        <button id="likes" data-catid="{{category.id}}"
            class="btn btn-primary" type="button">
            Like
        </button>
    {% endif %}
</div>


{% if pages %}
    <div class="pages">
        <ul>
        {% for page in pages %}
        <li>
            <a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
             <span class="tag tag-pill tag-primary">{{page.views}}</span>
        </li>
        {% endfor %}
        </ul>
    </div>
{% else %}
<div class="pages">
    <strong>No pages currently in category.</strong>
</div>
{% endif %}
{% else %}
The specified category does not exist!
{% endif %}
    {% if user.is_authenticated %}
        <form class="form-inline" id="user_form"
        method="post" action="{% url 'rango:show_category' category.slug %}">
        {% csrf_token %}
        <div class="form-group">
        <input class="form-control" type="text" size="50"
        name="query" value="{{ query }}" id="query" />
        </div>
        <button class="btn btn-primary" type="submit" name="submit"
        value="Search">Search</button>
        </form>

        <div>
        {% if result_list %}
        <h3>Results</h3>
        <!-- Display search results in an ordered list -->
        <div class="list-group">
        {% for result in result_list %}
            <div class="list-group-item">
            <h4 class="list-group-item-heading">
                <a href="{{ result.link }}">{{ result.title }}</a>
                <button data-catid="{{category.id}}" data-title="{{ result.title }}"
                    data-url="{{ result.link }}"
                    class="rango-add btn btn-info btn-sm" type="button">Add</button>
            </h4>
            <p class="list-group-item-text">{{ result.summary }}</p>

            </div>
        {% endfor %}
        </div>
            {% else %}


        {% endif %}

        </div>

  {% if not_find %}
    NOT FOUND
    {% endif %}
    {% endif %}


{% endblock %}

templates/rango/cats.html
<ul>
    {% for c in cats %}
        {% if c == act_cat %}
            <li>
            <strong>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </strong>
{#            <span class="tag tag-pill tag-primary">{{c.likes}}</span>#}
            </li>
        {% else %}
            <li>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </li>
{#            <span class="tag tag-pill tag-primary">{{c.likes}}</span>#}
        {% endif %}
    {% endfor %}
</ul>
<hr>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Index
{% endblock %}
{% block body_block %}
<div class="jumbotron">
<h1 class="display-3">Rango says...</h1>
{% if user.is_authenticated %}
<h1>hey there {{ user.username }}!</h1>
{% else %}
<h1>hey there partner! </h1>
{% endif %}
</div>
<div class="row marketing">
<div class="col-lg-6">
<h4>Most Liked Categories</h4>
<p>
{% if categories %}
<ul>
{% for category in categories %}
<li><a href="{% url 'rango:show_category' category.slug %}">
{{ category.name }}</a> <span class="tag tag-pill tag-primary">{{category.likes}}</span> </li>
{% endfor %}
</ul>
{% else %}
<strong>There are no categories present.</strong>
{% endif %}
</p>
</div>
<div class="col-lg-6">
    <h4>Most Viewed Pages</h4>
<p>
{% if pages %}
<ul>
{% for page in pages %}
<li>
   <a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
    <span class="tag tag-pill tag-primary">{{page.views}}</span>
</li>
{% endfor %}
</ul>
{% else %}
<strong>There are no categories present.</strong>
{% endif %}
</p>
</div>
</div>
<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
{% endblock %}

















{#{% extends 'rango/base.html' %}#}
{#{% load staticfiles %}#}
{#{% block title_block %}#}
{#{{ index }}#}
{#{% endblock %}#}
{#{% block body_block %}#}
{#    <p> visits: {{ visits }}</p>#}
{#    {% if user.is_authenticated %}#}
{#        howdy {{ user.username }}!#}
{#    {% else %}#}
{#        hey there partner!#}
{#    {% endif %}#}
{#{% if categories %}#}
{#    <h4>Most Liked Categories</h4>#}
{#<ul>#}
{##}
{#{% for category in categories %}#}
{#<!-- Following line changed to add an HTML hyperlink -->#}
{#<li>#}
{#<a href="{% url 'rango:show_category' category.slug %}">#}
{#    {{ category.name }}#}
{#</a>#}
{#</li>#}
{#{% endfor %}#}
{#</ul>#}
{#{% else %}#}
{#<strong>There are no categories present.</strong>#}
{#{% endif %}#}
{##}
{##}
{#<h4>Most Viewed Pages</h4>#}
{#{% if pages %}#}
{#    <ul>#}
{#        {% for page in pages %}#}
{#            <li>#}
{#            <a href="{{page.url}}">{{ page.title }}</a>#}
{#            </li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#{% else %}#}
{#    <strong>There are no pages present.</strong>#}
{#{% endif %}#}
{##}
{##}
{#<a href="{% url 'rango:about' %}">About</a>#}
{#<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />#}
{##}
{#{% endblock %}#}
{##}

templates/rango/page_list.html
{% if pages %}
    <ul>
        {% for page in pages %}
            <li>
                <a href="{% url 'rango:goto' %}?page_id={{ page.url }}">{{ page.title }}</a>
                <span class="tag tag-pill tag-primary">{{page.views}}</span>
            </li>

        {% endfor %}
    </ul>
{% else %}
    <strong>No pages currently in category.</strong>
{%  endif %}

templates/rango/profile_registration.html
{% extends "rango/base.html" %}
{% block title_block %}
    Registration - Step 2
    {% endblock %}
    {% block body_block %}
    <h1>Registration - Step 2</h1>
    <form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
{% endblock %}